//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firebase.Auth.UI.Resources
{
    using System;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources
    {

        private global::System.Resources.ResourceManager resourceMan;

        private global::System.Globalization.CultureInfo resourceCulture;
        private static AppResources instance;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResources()
        {
            instance = this;
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firebase.Auth.UI.Resources.AppResources", typeof(AppResources).Assembly);
                    this.resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current threads CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return this.resourceCulture;
            }
            set
            {
                this.resourceCulture = value;
            }
        }

        public static AppResources Instance
        {
            get
            {
                return instance ?? (instance = new AppResources());
            }
        }

        /// <summary>
        /// ui_flow
        /// </summary>
		public string AppName
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("app_name", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"ui_flow" : x;
                }
                catch
                {
                    return @"ui_flow";
                }
            }
        }

        /// <summary>
        /// @string/app_name
        /// </summary>
		public string FuiDefaultToolbarTitle
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_default_toolbar_title", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"@string/app_name" : x;
                }
                catch
                {
                    return @"@string/app_name";
                }
            }
        }

        /// <summary>
        /// Loadingâ€¦
        /// </summary>
		public string FuiProgressDialogLoading
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_progress_dialog_loading", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Loadingâ€¦" : x;
                }
                catch
                {
                    return @"Loadingâ€¦";
                }
            }
        }

        /// <summary>
        /// Sign in
        /// </summary>
		public string FuiSignInDefault
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_default", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in" : x;
                }
                catch
                {
                    return @"Sign in";
                }
            }
        }

        /// <summary>
        /// Cancel
        /// </summary>
		public string FuiCancel
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_cancel", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Cancel" : x;
                }
                catch
                {
                    return @"Cancel";
                }
            }
        }

        /// <summary>
        /// Continue
        /// </summary>
		public string FuiContinue
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_continue", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Continue" : x;
                }
                catch
                {
                    return @"Continue";
                }
            }
        }

        /// <summary>
        /// By continuing, you are indicating that you accept our %1$s and %2$s.
        /// </summary>
		public string FuiTosAndPp
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_tos_and_pp", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"By continuing, you are indicating that you accept our %1$s and %2$s." : x;
                }
                catch
                {
                    return @"By continuing, you are indicating that you accept our %1$s and %2$s.";
                }
            }
        }

        /// <summary>
        /// %1$s \u00A0 \u00A0 %2$s
        /// </summary>
		public string FuiTosAndPpFooter
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_tos_and_pp_footer", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"%1$s \u00A0 \u00A0 %2$s" : x;
                }
                catch
                {
                    return @"%1$s \u00A0 \u00A0 %2$s";
                }
            }
        }

        /// <summary>
        /// Network error, check your internet connection.
        /// </summary>
		public string FuiNoInternet
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_no_internet", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Network error, check your internet connection." : x;
                }
                catch
                {
                    return @"Network error, check your internet connection.";
                }
            }
        }

        /// <summary>
        /// Google
        /// </summary>
		public string FuiIdpNameGoogle
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_idp_name_google", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Google" : x;
                }
                catch
                {
                    return @"Google";
                }
            }
        }

        /// <summary>
        /// Facebook
        /// </summary>
		public string FuiIdpNameFacebook
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_idp_name_facebook", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Facebook" : x;
                }
                catch
                {
                    return @"Facebook";
                }
            }
        }

        /// <summary>
        /// Twitter
        /// </summary>
		public string FuiIdpNameTwitter
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_idp_name_twitter", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Twitter" : x;
                }
                catch
                {
                    return @"Twitter";
                }
            }
        }

        /// <summary>
        /// GitHub
        /// </summary>
		public string FuiIdpNameGithub
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_idp_name_github", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"GitHub" : x;
                }
                catch
                {
                    return @"GitHub";
                }
            }
        }

        /// <summary>
        /// Phone
        /// </summary>
		public string FuiIdpNamePhone
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_idp_name_phone", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Phone" : x;
                }
                catch
                {
                    return @"Phone";
                }
            }
        }

        /// <summary>
        /// Email
        /// </summary>
		public string FuiIdpNameEmail
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_idp_name_email", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Email" : x;
                }
                catch
                {
                    return @"Email";
                }
            }
        }

        /// <summary>
        /// Sign in with Google
        /// </summary>
		public string FuiSignInWithGoogle
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_google", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with Google" : x;
                }
                catch
                {
                    return @"Sign in with Google";
                }
            }
        }

        /// <summary>
        /// Sign in with Facebook
        /// </summary>
		public string FuiSignInWithFacebook
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_facebook", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with Facebook" : x;
                }
                catch
                {
                    return @"Sign in with Facebook";
                }
            }
        }

        /// <summary>
        /// Sign in with Twitter
        /// </summary>
		public string FuiSignInWithTwitter
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_twitter", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with Twitter" : x;
                }
                catch
                {
                    return @"Sign in with Twitter";
                }
            }
        }

        /// <summary>
        /// Sign in with GitHub
        /// </summary>
		public string FuiSignInWithGithub
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_github", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with GitHub" : x;
                }
                catch
                {
                    return @"Sign in with GitHub";
                }
            }
        }

        /// <summary>
        /// Sign in with email
        /// </summary>
		public string FuiSignInWithEmail
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_email", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with email" : x;
                }
                catch
                {
                    return @"Sign in with email";
                }
            }
        }

        /// <summary>
        /// Sign in with phone
        /// </summary>
		public string FuiSignInWithPhone
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_phone", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with phone" : x;
                }
                catch
                {
                    return @"Sign in with phone";
                }
            }
        }

        /// <summary>
        /// Continue as guest
        /// </summary>
		public string FuiSignInAnonymously
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_anonymously", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Continue as guest" : x;
                }
                catch
                {
                    return @"Continue as guest";
                }
            }
        }

        /// <summary>
        /// Sign in with Apple
        /// </summary>
		public string FuiSignInWithApple
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_apple", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with Apple" : x;
                }
                catch
                {
                    return @"Sign in with Apple";
                }
            }
        }

        /// <summary>
        /// Sign in with Microsoft
        /// </summary>
		public string FuiSignInWithMicrosoft
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_microsoft", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with Microsoft" : x;
                }
                catch
                {
                    return @"Sign in with Microsoft";
                }
            }
        }

        /// <summary>
        /// Sign in with Yahoo
        /// </summary>
		public string FuiSignInWithYahoo
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_yahoo", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with Yahoo" : x;
                }
                catch
                {
                    return @"Sign in with Yahoo";
                }
            }
        }

        /// <summary>
        /// Next
        /// </summary>
		public string FuiNextDefault
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_next_default", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Next" : x;
                }
                catch
                {
                    return @"Next";
                }
            }
        }

        /// <summary>
        /// Email
        /// </summary>
		public string FuiEmailHint
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_hint", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Email" : x;
                }
                catch
                {
                    return @"Email";
                }
            }
        }

        /// <summary>
        /// Phone Number
        /// </summary>
		public string FuiPhoneHint
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_phone_hint", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Phone Number" : x;
                }
                catch
                {
                    return @"Phone Number";
                }
            }
        }

        /// <summary>
        /// Password
        /// </summary>
		public string FuiPasswordHint
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_password_hint", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Password" : x;
                }
                catch
                {
                    return @"Password";
                }
            }
        }

        /// <summary>
        /// You can\'t leave this empty.
        /// </summary>
		public string FuiRequiredField
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_required_field", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"You can\'t leave this empty." : x;
                }
                catch
                {
                    return @"You can\'t leave this empty.";
                }
            }
        }

        /// <summary>
        /// That email address isn\'t correct
        /// </summary>
		public string FuiInvalidEmailAddress
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_invalid_email_address", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"That email address isn\'t correct" : x;
                }
                catch
                {
                    return @"That email address isn\'t correct";
                }
            }
        }

        /// <summary>
        /// Enter your email address to continue
        /// </summary>
		public string FuiMissingEmailAddress
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_missing_email_address", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Enter your email address to continue" : x;
                }
                catch
                {
                    return @"Enter your email address to continue";
                }
            }
        }

        /// <summary>
        /// Please enter a first and last name.
        /// </summary>
		public string FuiMissingFirstAndLastName
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_missing_first_and_last_name", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Please enter a first and last name." : x;
                }
                catch
                {
                    return @"Please enter a first and last name.";
                }
            }
        }

        /// <summary>
        /// Checking for existing accountsâ€¦
        /// </summary>
		public string FuiProgressDialogCheckingAccounts
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_progress_dialog_checking_accounts", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Checking for existing accountsâ€¦" : x;
                }
                catch
                {
                    return @"Checking for existing accountsâ€¦";
                }
            }
        }

        /// <summary>
        /// Sign up
        /// </summary>
		public string FuiTitleRegisterEmail
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_title_register_email", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign up" : x;
                }
                catch
                {
                    return @"Sign up";
                }
            }
        }

        /// <summary>
        /// First &amp; last name
        /// </summary>
		public string FuiNameHint
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_name_hint", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"First & last name" : x;
                }
                catch
                {
                    return @"First & last name";
                }
            }
        }

        /// <summary>
        /// Save
        /// </summary>
		public string FuiButtonTextSave
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_button_text_save", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Save" : x;
                }
                catch
                {
                    return @"Save";
                }
            }
        }

        /// <summary>
        /// Signing upâ€¦
        /// </summary>
		public string FuiProgressDialogSigningUp
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_progress_dialog_signing_up", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Signing upâ€¦" : x;
                }
                catch
                {
                    return @"Signing upâ€¦";
                }
            }
        }

        /// <summary>
        /// Email account registration unsuccessful
        /// </summary>
		public string FuiEmailAccountCreationError
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_account_creation_error", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Email account registration unsuccessful" : x;
                }
                catch
                {
                    return @"Email account registration unsuccessful";
                }
            }
        }

        /// <summary>
        /// Terms of Service
        /// </summary>
		public string FuiTermsOfService
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_terms_of_service", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Terms of Service" : x;
                }
                catch
                {
                    return @"Terms of Service";
                }
            }
        }

        /// <summary>
        /// Privacy Policy
        /// </summary>
		public string FuiPrivacyPolicy
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_privacy_policy", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Privacy Policy" : x;
                }
                catch
                {
                    return @"Privacy Policy";
                }
            }
        }

        /// <summary>
        /// email_field
        /// </summary>
		public string FuiEmailFieldName
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_field_name", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"email_field" : x;
                }
                catch
                {
                    return @"email_field";
                }
            }
        }

        /// <summary>
        /// @string/fui_sign_in_default
        /// </summary>
		public string FuiTitleWelcomeBackIdpPrompt
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_title_welcome_back_idp_prompt", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"@string/fui_sign_in_default" : x;
                }
                catch
                {
                    return @"@string/fui_sign_in_default";
                }
            }
        }

        /// <summary>
        /// @string/fui_sign_in_default
        /// </summary>
		public string FuiTitleWelcomeBackPasswordPrompt
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_title_welcome_back_password_prompt", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"@string/fui_sign_in_default" : x;
                }
                catch
                {
                    return @"@string/fui_sign_in_default";
                }
            }
        }

        /// <summary>
        /// You already have an account
        /// </summary>
		public string FuiWelcomeBackIdpHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_welcome_back_idp_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"You already have an account" : x;
                }
                catch
                {
                    return @"You already have an account";
                }
            }
        }

        /// <summary>
        /// Welcome back!
        /// </summary>
		public string FuiWelcomeBackEmailHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_welcome_back_email_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Welcome back!" : x;
                }
                catch
                {
                    return @"Welcome back!";
                }
            }
        }

        /// <summary>
        /// You already have an account\n
        /// </summary>
		public string FuiWelcomeBackEmailLinkHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_welcome_back_email_link_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"You already have an account\n" : x;
                }
                catch
                {
                    return @"You already have an account\n";
                }
            }
        }

        /// <summary>
        ///          You\'ve already used %1$s.         Sign in with %2$s to continue.     
        /// </summary>
		public string FuiWelcomeBackIdpPrompt
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_welcome_back_idp_prompt", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"         You\'ve already used %1$s.         Sign in with %2$s to continue.     " : x;
                }
                catch
                {
                    return @"         You\'ve already used %1$s.         Sign in with %2$s to continue.     ";
                }
            }
        }

        /// <summary>
        ///          You\'ve already used %1$s         to sign in. Enter your password for that account.     
        /// </summary>
		public string FuiWelcomeBackPasswordPromptBody
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_welcome_back_password_prompt_body", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"         You\'ve already used %1$s         to sign in. Enter your password for that account.     " : x;
                }
                catch
                {
                    return @"         You\'ve already used %1$s         to sign in. Enter your password for that account.     ";
                }
            }
        }

        /// <summary>
        ///          You\'ve already used %1$s.         You can connect your %2$s account with %1$s by signing in with email link below.\n\nFor this flow to successfully connect your %2$s account with this email, you have to open the link on the same device or browser.     
        /// </summary>
		public string FuiWelcomeBackEmailLinkPromptBody
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_welcome_back_email_link_prompt_body", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"         You\'ve already used %1$s.         You can connect your %2$s account with %1$s by signing in with email link below.\n\nFor this flow to successfully connect your %2$s account with this email, you have to open the link on the same device or browser.     " : x;
                }
                catch
                {
                    return @"         You\'ve already used %1$s.         You can connect your %2$s account with %1$s by signing in with email link below.\n\nFor this flow to successfully connect your %2$s account with this email, you have to open the link on the same device or browser.     ";
                }
            }
        }

        /// <summary>
        /// Signing inâ€¦
        /// </summary>
		public string FuiProgressDialogSigningIn
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_progress_dialog_signing_in", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Signing inâ€¦" : x;
                }
                catch
                {
                    return @"Signing inâ€¦";
                }
            }
        }

        /// <summary>
        /// Trouble signing in?
        /// </summary>
		public string FuiTroubleSigningIn
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_trouble_signing_in", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Trouble signing in?" : x;
                }
                catch
                {
                    return @"Trouble signing in?";
                }
            }
        }

        /// <summary>
        /// Recover password
        /// </summary>
		public string FuiTitleRecoverPasswordActivity
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_title_recover_password_activity", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Recover password" : x;
                }
                catch
                {
                    return @"Recover password";
                }
            }
        }

        /// <summary>
        /// Check your email
        /// </summary>
		public string FuiTitleConfirmRecoverPassword
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_title_confirm_recover_password", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Check your email" : x;
                }
                catch
                {
                    return @"Check your email";
                }
            }
        }

        /// <summary>
        /// Get instructions sent to this email that explain how to         reset your password.
        /// </summary>
		public string FuiPasswordRecoveryBody
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_password_recovery_body", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Get instructions sent to this email that explain how to         reset your password." : x;
                }
                catch
                {
                    return @"Get instructions sent to this email that explain how to         reset your password.";
                }
            }
        }

        /// <summary>
        /// Send
        /// </summary>
		public string FuiButtonTextSend
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_button_text_send", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Send" : x;
                }
                catch
                {
                    return @"Send";
                }
            }
        }

        /// <summary>
        /// Follow the instructions sent to %1$s to recover your password.
        /// </summary>
		public string FuiConfirmRecoveryBody
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_confirm_recovery_body", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Follow the instructions sent to %1$s to recover your password." : x;
                }
                catch
                {
                    return @"Follow the instructions sent to %1$s to recover your password.";
                }
            }
        }

        /// <summary>
        /// Sendingâ€¦
        /// </summary>
		public string FuiProgressDialogSending
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_progress_dialog_sending", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sendingâ€¦" : x;
                }
                catch
                {
                    return @"Sendingâ€¦";
                }
            }
        }

        /// <summary>
        /// That email address doesn\'t match an existing account
        /// </summary>
		public string FuiErrorEmailDoesNotExist
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_error_email_does_not_exist", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"That email address doesn\'t match an existing account" : x;
                }
                catch
                {
                    return @"That email address doesn\'t match an existing account";
                }
            }
        }

        /// <summary>
        /// An unknown error occurred.
        /// </summary>
		public string FuiErrorUnknown
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_error_unknown", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"An unknown error occurred." : x;
                }
                catch
                {
                    return @"An unknown error occurred.";
                }
            }
        }

        /// <summary>
        /// Incorrect password.
        /// </summary>
		public string FuiErrorInvalidPassword
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_error_invalid_password", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Incorrect password." : x;
                }
                catch
                {
                    return @"Incorrect password.";
                }
            }
        }

        /// <summary>
        /// App logo
        /// </summary>
		public string FuiAccessibilityLogo
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_accessibility_logo", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"App logo" : x;
                }
                catch
                {
                    return @"App logo";
                }
            }
        }

        /// <summary>
        /// Sign-in email sent\n
        /// </summary>
		public string FuiEmailLinkHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign-in email sent\n" : x;
                }
                catch
                {
                    return @"Sign-in email sent\n";
                }
            }
        }

        /// <summary>
        /// A sign-in email with additional instructions was sent to %1$s. Check your email to complete sign-in.
        /// </summary>
		public string FuiEmailLinkEmailSent
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_email_sent", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"A sign-in email with additional instructions was sent to %1$s. Check your email to complete sign-in." : x;
                }
                catch
                {
                    return @"A sign-in email with additional instructions was sent to %1$s. Check your email to complete sign-in.";
                }
            }
        }

        /// <summary>
        /// Trouble getting email?
        /// </summary>
		public string FuiEmailLinkTroubleGettingEmailHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_trouble_getting_email_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Trouble getting email?" : x;
                }
                catch
                {
                    return @"Trouble getting email?";
                }
            }
        }

        /// <summary>
        /// Try these common fixes:\n\u2022 Check if the email was marked as spam or filtered.\n\u2022 Check your internet connection.\n\u2022 Check that you did not misspell your email.\n\u2022 Check that your inbox space is not running out or other inbox setting related issues.\n
        /// </summary>
		public string FuiEmailLinkTroubleGettingPossibleFixes
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_trouble_getting_possible_fixes", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Try these common fixes:\n\u2022 Check if the email was marked as spam or filtered.\n\u2022 Check your internet connection.\n\u2022 Check that you did not misspell your email.\n\u2022 Check that your inbox space is not running out or other inbox setting related issues.\n" : x;
                }
                catch
                {
                    return @"Try these common fixes:\n\u2022 Check if the email was marked as spam or filtered.\n\u2022 Check your internet connection.\n\u2022 Check that you did not misspell your email.\n\u2022 Check that your inbox space is not running out or other inbox setting related issues.\n";
                }
            }
        }

        /// <summary>
        /// If the steps above didn\'t work, you can resend the email. Note that this will deactivate the link in the older email. 
        /// </summary>
		public string FuiEmailLinkTroubleGettingEmailResendSolution
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_trouble_getting_email_resend_solution", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"If the steps above didn\'t work, you can resend the email. Note that this will deactivate the link in the older email. " : x;
                }
                catch
                {
                    return @"If the steps above didn\'t work, you can resend the email. Note that this will deactivate the link in the older email. ";
                }
            }
        }

        /// <summary>
        /// Resend
        /// </summary>
		public string FuiEmailLinkResend
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_resend", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Resend" : x;
                }
                catch
                {
                    return @"Resend";
                }
            }
        }

        /// <summary>
        /// New device or browser detected.
        /// </summary>
		public string FuiEmailLinkWrongDeviceHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_wrong_device_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"New device or browser detected." : x;
                }
                catch
                {
                    return @"New device or browser detected.";
                }
            }
        }

        /// <summary>
        /// Try opening the link using the same device or browser where you started the sign-in process.
        /// </summary>
		public string FuiEmailLinkWrongDeviceMessage
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_wrong_device_message", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Try opening the link using the same device or browser where you started the sign-in process." : x;
                }
                catch
                {
                    return @"Try opening the link using the same device or browser where you started the sign-in process.";
                }
            }
        }

        /// <summary>
        /// Unable to complete sign in
        /// </summary>
		public string FuiEmailLinkInvalidLinkHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_invalid_link_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Unable to complete sign in" : x;
                }
                catch
                {
                    return @"Unable to complete sign in";
                }
            }
        }

        /// <summary>
        /// The action code is invalid. This can happen if the code is malformed, expired, or has already been used.
        /// </summary>
		public string FuiEmailLinkInvalidLinkMessage
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_invalid_link_message", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"The action code is invalid. This can happen if the code is malformed, expired, or has already been used." : x;
                }
                catch
                {
                    return @"The action code is invalid. This can happen if the code is malformed, expired, or has already been used.";
                }
            }
        }

        /// <summary>
        /// Session ended
        /// </summary>
		public string FuiEmailLinkDifferentAnonymousUserHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_different_anonymous_user_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Session ended" : x;
                }
                catch
                {
                    return @"Session ended";
                }
            }
        }

        /// <summary>
        /// The session associated with this sign-in request has either expired or was cleared.
        /// </summary>
		public string FuiEmailLinkDifferentAnonymousUserMessage
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_different_anonymous_user_message", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"The session associated with this sign-in request has either expired or was cleared." : x;
                }
                catch
                {
                    return @"The session associated with this sign-in request has either expired or was cleared.";
                }
            }
        }

        /// <summary>
        /// Confirm email
        /// </summary>
		public string FuiEmailLinkConfirmEmailHeader
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_confirm_email_header", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Confirm email" : x;
                }
                catch
                {
                    return @"Confirm email";
                }
            }
        }

        /// <summary>
        /// Confirm email to continue sign in
        /// </summary>
		public string FuiEmailLinkConfirmEmailMessage
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_confirm_email_message", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Confirm email to continue sign in" : x;
                }
                catch
                {
                    return @"Confirm email to continue sign in";
                }
            }
        }

        /// <summary>
        /// Dismiss
        /// </summary>
		public string FuiEmailLinkDismissButton
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_dismiss_button", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Dismiss" : x;
                }
                catch
                {
                    return @"Dismiss";
                }
            }
        }

        /// <summary>
        /// You originally intended to connect %1$s to your email account but have opened the link on a different device where you are not signed in.\n\nIf you still want to connect your %1$s account, open the link on the same device where you started sign-in. Otherwise, tap Continue to sign-in on this device.
        /// </summary>
		public string FuiEmailLinkCrossDeviceLinkingText
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_cross_device_linking_text", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"You originally intended to connect %1$s to your email account but have opened the link on a different device where you are not signed in.\n\nIf you still want to connect your %1$s account, open the link on the same device where you started sign-in. Otherwise, tap Continue to sign-in on this device." : x;
                }
                catch
                {
                    return @"You originally intended to connect %1$s to your email account but have opened the link on a different device where you are not signed in.\n\nIf you still want to connect your %1$s account, open the link on the same device where you started sign-in. Otherwise, tap Continue to sign-in on this device.";
                }
            }
        }

        /// <summary>
        /// Sign in with %1$s
        /// </summary>
		public string FuiEmailLinkCrossDeviceSignInButtonText
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_email_link_cross_device_sign_in_button_text", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with %1$s" : x;
                }
                catch
                {
                    return @"Sign in with %1$s";
                }
            }
        }

        /// <summary>
        /// Enter your phone number
        /// </summary>
		public string FuiVerifyPhoneNumberTitle
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_verify_phone_number_title", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Enter your phone number" : x;
                }
                catch
                {
                    return @"Enter your phone number";
                }
            }
        }

        /// <summary>
        /// Enter a valid phone number
        /// </summary>
		public string FuiInvalidPhoneNumber
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_invalid_phone_number", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Enter a valid phone number" : x;
                }
                catch
                {
                    return @"Enter a valid phone number";
                }
            }
        }

        /// <summary>
        /// Enter the 6-digit code we sent to
        /// </summary>
		public string FuiEnterConfirmationCode
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_enter_confirmation_code", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Enter the 6-digit code we sent to" : x;
                }
                catch
                {
                    return @"Enter the 6-digit code we sent to";
                }
            }
        }

        /// <summary>
        /// Resend code in 0:%02d
        /// </summary>
		public string FuiResendCodeIn
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_resend_code_in", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Resend code in 0:%02d" : x;
                }
                catch
                {
                    return @"Resend code in 0:%02d";
                }
            }
        }

        /// <summary>
        /// Verify your phone number
        /// </summary>
		public string FuiVerifyYourPhoneTitle
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_verify_your_phone_title", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Verify your phone number" : x;
                }
                catch
                {
                    return @"Verify your phone number";
                }
            }
        }

        /// <summary>
        /// Verifyingâ€¦
        /// </summary>
		public string FuiVerifying
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_verifying", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Verifyingâ€¦" : x;
                }
                catch
                {
                    return @"Verifyingâ€¦";
                }
            }
        }

        /// <summary>
        /// Wrong code. Try again.
        /// </summary>
		public string FuiIncorrectCodeDialogBody
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_incorrect_code_dialog_body", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Wrong code. Try again." : x;
                }
                catch
                {
                    return @"Wrong code. Try again.";
                }
            }
        }

        /// <summary>
        /// This phone number has been used too many times
        /// </summary>
		public string FuiErrorTooManyAttempts
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_error_too_many_attempts", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"This phone number has been used too many times" : x;
                }
                catch
                {
                    return @"This phone number has been used too many times";
                }
            }
        }

        /// <summary>
        /// There was a problem verifying your phone number
        /// </summary>
		public string FuiErrorQuotaExceeded
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_error_quota_exceeded", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"There was a problem verifying your phone number" : x;
                }
                catch
                {
                    return @"There was a problem verifying your phone number";
                }
            }
        }

        /// <summary>
        /// This code is no longer valid
        /// </summary>
		public string FuiErrorSessionExpired
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_error_session_expired", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"This code is no longer valid" : x;
                }
                catch
                {
                    return @"This code is no longer valid";
                }
            }
        }

        /// <summary>
        /// Sign in with phone number
        /// </summary>
		public string FuiSignInWithPhoneNumber
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sign_in_with_phone_number", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Sign in with phone number" : x;
                }
                catch
                {
                    return @"Sign in with phone number";
                }
            }
        }

        /// <summary>
        /// Phone number automatically verified
        /// </summary>
		public string FuiAutoVerified
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_auto_verified", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Phone number automatically verified" : x;
                }
                catch
                {
                    return @"Phone number automatically verified";
                }
            }
        }

        /// <summary>
        /// Resend Code
        /// </summary>
		public string FuiResendCode
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_resend_code", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Resend Code" : x;
                }
                catch
                {
                    return @"Resend Code";
                }
            }
        }

        /// <summary>
        /// Verify Phone Number
        /// </summary>
		public string FuiVerifyPhoneNumber
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_verify_phone_number", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Verify Phone Number" : x;
                }
                catch
                {
                    return @"Verify Phone Number";
                }
            }
        }

        /// <summary>
        /// By tapping â€œ%1$sâ€, an SMS may be sent. Message &amp; data rates may apply.
        /// </summary>
		public string FuiSmsTermsOfService
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sms_terms_of_service", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"By tapping â€œ%1$sâ€, an SMS may be sent. Message & data rates may apply." : x;
                }
                catch
                {
                    return @"By tapping â€œ%1$sâ€, an SMS may be sent. Message & data rates may apply.";
                }
            }
        }

        /// <summary>
        /// By tapping â€œ%1$sâ€, you are indicating that you accept our %2$s and %3$s. An SMS may be sent. Message &amp; data rates may apply.
        /// </summary>
		public string FuiSmsTermsOfServiceAndPrivacyPolicyExtended
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_sms_terms_of_service_and_privacy_policy_extended", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"By tapping â€œ%1$sâ€, you are indicating that you accept our %2$s and %3$s. An SMS may be sent. Message & data rates may apply." : x;
                }
                catch
                {
                    return @"By tapping â€œ%1$sâ€, you are indicating that you accept our %2$s and %3$s. An SMS may be sent. Message & data rates may apply.";
                }
            }
        }

        /// <summary>
        /// Password not strong enough. Use at least %1$d character and a mix of letters and numbers
        /// </summary>
		public string FuiErrorWeakPasswordOne
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_error_weak_password_one", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Password not strong enough. Use at least %1$d character and a mix of letters and numbers" : x;
                }
                catch
                {
                    return @"Password not strong enough. Use at least %1$d character and a mix of letters and numbers";
                }
            }
        }

        /// <summary>
        /// Password not strong enough. Use at least %1$d characters and a mix of letters and numbers
        /// </summary>
		public string FuiErrorWeakPasswordOther
        {
            get
            {
                try
                {
                    var x = ResourceManager.GetString("fui_error_weak_password_other", this.resourceCulture);
                    return string.IsNullOrWhiteSpace(x) ? @"Password not strong enough. Use at least %1$d characters and a mix of letters and numbers" : x;
                }
                catch
                {
                    return @"Password not strong enough. Use at least %1$d characters and a mix of letters and numbers";
                }
            }
        }

        public string FuiErrorWeakPasswordWithCount(int count)
        {
            var key = "";
            switch (count)
            {
                case 1:
                    key = "fui_error_weak_password_one";
                    break;
                case var c when (c < 5):
                    key = "fui_error_weak_password_few";
                    break;
                default:
                    key = "fui_error_weak_password_other";
                    break; ;
            };
            var x = ResourceManager.GetString(key, this.resourceCulture);
            return string.IsNullOrWhiteSpace(x) ? @"fui_error_weak_password" : string.Format(x, count);
        }

    }
}
