using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using pglMagicRename.Properties;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace pglMagicRename.MVVM.View
{
    partial class MainForm
    {

        private Document doc;
        private UIDocument uidoc;
        private MainFormUtils mfu;
        private AuthUtils auth;
        private Application app;
        private int maxItemsTrial = 5;
        private System.Drawing.Color defBackColor;
        private bool formShown;
        private bool[] asc;
        private int sCount;
        private FilteredElementCollector objColl;
        private List<Element> objList;
        private string errorString = "[ERROR]";
        private string appName = "Magic Rename Tool";
        private int objType;
        private string objTypeName;
        private string objTypeNamePl;
        private bool onlySelection;
        private bool activeFilter;
        private int indId = 0;
        private int indCat = 1;
        private int indFam = 2;
        private int indOld;
        private int indNew;
        private double numbFirst;
        private double numbStep;
        private double numbCurrent;
        private bool numbOk;
        private System.Windows.Forms.Timer timerCheck;
        private int firstClickItemIndex = 0;
        private ListViewItem _itemDnD = (ListViewItem)null;
        private IContainer components = (IContainer)null;
        private Label label5;
        private LinkLabel linkLabel1;
        private ColumnHeader columnHeader1;
        private ColumnHeader columnHeader2;
        private ColumnHeader columnHeader3;
        private Button button1;
        private Label label1;
        private Label label2;
        private GroupBox groupBox1;
        private System.Windows.Controls.TextBox textBox1;
        private Label label7;
        private Label label6;
        private Label label3;
        private NumericUpDown numericUpDown1;
        private GroupBox groupBox2;
        private TextBox textBox2;
        private Label label9;
        private System.Windows.Forms.ComboBox comboBox1;
        private Label label8;
        private Button button2;
        private GroupBox groupBox3;
        private System.Windows.Forms.TextBox textBox3;
        private Label label10;
        private Label label11;
        private Label label12;
        private NumericUpDown numericUpDown2;
        private ColumnHeader columnHeader4;
        private GroupBox groupBox4;
        private TextBox textBox5;
        private TextBox textBox4;
        private Label label13;
        private Label label15;
        private Button button3;
        private Button button4;
        private Button button5;
        private LinkLabel linkLabelSite;
        private Label labelSite;
        private PictureBox pictureBoxSite;
        private Label label14;
        private GroupBox groupBox5;
        private Label label19;
        private NumericUpDown numericUpDown4;
        private TextBox textBox6;
        private Label label16;
        private Label label17;
        private Label label18;
        private NumericUpDown numericUpDown3;
        private CheckBox checkBox1;
        private CheckBox checkBox2;
        private CheckBox checkBox3;
        private Label label20;
        private Label label21;
        private ListViewEx listView1;
        private PictureBox pictureBox3;
        private Label label22;
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(MainForm));
            this.label5 = new Label();
            this.linkLabel1 = new LinkLabel();
            this.button1 = new Button();
            this.label1 = new Label();
            this.label2 = new Label();
            this.groupBox1 = new GroupBox();
            this.textBox1 = new TextBox();
            this.label7 = new Label();
            this.label6 = new Label();
            this.label3 = new Label();
            this.numericUpDown1 = new NumericUpDown();
            this.groupBox2 = new GroupBox();
            this.button4 = new Button();
            this.button3 = new Button();
            this.textBox2 = new TextBox();
            this.label9 = new Label();
            this.comboBox1 = new ComboBox();
            this.label8 = new Label();
            this.button2 = new Button();
            this.groupBox3 = new GroupBox();
            this.textBox3 = new TextBox();
            this.label10 = new Label();
            this.label11 = new Label();
            this.label12 = new Label();
            this.numericUpDown2 = new NumericUpDown();
            this.groupBox4 = new GroupBox();
            this.textBox5 = new TextBox();
            this.textBox4 = new TextBox();
            this.label13 = new Label();
            this.label15 = new Label();
            this.button5 = new Button();
            this.linkLabelSite = new LinkLabel();
            this.labelSite = new Label();
            this.label14 = new Label();
            this.groupBox5 = new GroupBox();
            this.label19 = new Label();
            this.numericUpDown4 = new NumericUpDown();
            this.textBox6 = new TextBox();
            this.label16 = new Label();
            this.label17 = new Label();
            this.label18 = new Label();
            this.numericUpDown3 = new NumericUpDown();
            this.checkBox1 = new CheckBox();
            this.checkBox2 = new CheckBox();
            this.checkBox3 = new CheckBox();
            this.label20 = new Label();
            this.label21 = new Label();
            this.label22 = new Label();
            this.listView1 = new ListViewEx();
            this.columnHeader4 = new ColumnHeader();
            this.columnHeader1 = new ColumnHeader();
            this.columnHeader2 = new ColumnHeader();
            this.columnHeader3 = new ColumnHeader();
            this.pictureBox3 = new PictureBox();
            this.pictureBoxSite = new PictureBox();
            this.groupBox1.SuspendLayout();
            this.numericUpDown1.BeginInit();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.numericUpDown2.BeginInit();
            this.groupBox4.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.numericUpDown4.BeginInit();
            this.numericUpDown3.BeginInit();
            ((ISupportInitialize)this.pictureBox3).BeginInit();
            ((ISupportInitialize)this.pictureBoxSite).BeginInit();
            this.SuspendLayout();
            this.label5.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.label5.Font = new Font("Microsoft Sans Serif", 7.5f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
            this.label5.Location = new System.Drawing.Point(778, 580);
            this.label5.Margin = new Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new Size(123, 13);
            this.label5.TabIndex = 4;
            this.label5.Text = "v1.5, June 2022";
            this.label5.UseCompatibleTextRendering = true;
            this.linkLabel1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.linkLabel1.AutoSize = true;
            this.linkLabel1.Font = new Font("Microsoft Sans Serif", 7.5f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
            this.linkLabel1.Location = new System.Drawing.Point(14, 597);
            this.linkLabel1.Name = "linkLabel1";
            this.linkLabel1.Size = new Size(0, 16);
            this.linkLabel1.TabIndex = 5;
            this.linkLabel1.UseCompatibleTextRendering = true;
            this.button1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.button1.Enabled = false;
            this.button1.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
            this.button1.Location = new System.Drawing.Point(280, 580);
            this.button1.Name = "button1";
            this.button1.Size = new Size(481, 34);
            this.button1.TabIndex = 11;
            this.button1.Text = "Rename Families";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.button1_Click);
            this.label1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(280, 564);
            this.label1.Name = "label1";
            this.label1.Size = new Size(269, 13);
            this.label1.TabIndex = 8;
            this.label1.Text = "Check in the list above the families you want to rename.";
            this.label2.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(187, 535);
            this.label2.Name = "label2";
            this.label2.Size = new Size(35, 13);
            this.label2.TabIndex = 9;
            this.label2.Text = "label2";
            this.groupBox1.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.groupBox1.Controls.Add((Control)this.textBox1);
            this.groupBox1.Controls.Add((Control)this.label7);
            this.groupBox1.Controls.Add((Control)this.label6);
            this.groupBox1.Controls.Add((Control)this.label3);
            this.groupBox1.Controls.Add((Control)this.numericUpDown1);
            this.groupBox1.Location = new Point(778, 87);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(168, 74);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Prefix";
            this.textBox1.Location = new Point(82, 43);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(78, 20);
            this.textBox1.TabIndex = 6;
            this.textBox1.TextChanged += new EventHandler(this.textBox1_TextChanged);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(8, 46);
            this.label7.Name = "label7";
            this.label7.Size = new Size(57, 13);
            this.label7.TabIndex = 3;
            this.label7.Text = "Add prefix:";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(125, 20);
            this.label6.Name = "label6";
            this.label6.Size = new Size(33, 13);
            this.label6.TabIndex = 2;
            this.label6.Text = "chars";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(8, 20);
            this.label3.Name = "label3";
            this.label3.Size = new Size(66, 13);
            this.label3.TabIndex = 1;
            this.label3.Text = "Remove first";
            this.numericUpDown1.Location = new Point(82, 18);
            this.numericUpDown1.Maximum = new Decimal(new int[4]
            {
        99,
        0,
        0,
        0
            });
            this.numericUpDown1.Name = "numericUpDown1";
            this.numericUpDown1.Size = new Size(38, 20);
            this.numericUpDown1.TabIndex = 5;
            this.numericUpDown1.ValueChanged += new EventHandler(this.numericUpDown1_ValueChanged);
            this.groupBox2.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.groupBox2.Controls.Add((Control)this.button4);
            this.groupBox2.Controls.Add((Control)this.button3);
            this.groupBox2.Controls.Add((Control)this.textBox2);
            this.groupBox2.Controls.Add((Control)this.label9);
            this.groupBox2.Controls.Add((Control)this.comboBox1);
            this.groupBox2.Controls.Add((Control)this.label8);
            this.groupBox2.Location = new Point(15, 13);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(928, 43);
            this.groupBox2.TabIndex = 0;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Filters";
            this.button4.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.button4.Location = new Point(865, 13);
            this.button4.Name = "button4";
            this.button4.Size = new Size(56, 22);
            this.button4.TabIndex = 4;
            this.button4.Text = "Show all";
            this.button4.UseVisualStyleBackColor = true;
            this.button4.Click += new EventHandler(this.button4_Click);
            this.button3.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.button3.Location = new Point(812, 13);
            this.button3.Name = "button3";
            this.button3.Size = new Size(50, 22);
            this.button3.TabIndex = 3;
            this.button3.Text = "Filter";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new EventHandler(this.button3_Click);
            this.textBox2.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.textBox2.Location = new Point(717, 14);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new Size(89, 20);
            this.textBox2.TabIndex = 2;
            this.label9.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label9.Location = new Point(460, 18);
            this.label9.Name = "label9";
            this.label9.Size = new Size(245, 13);
            this.label9.TabIndex = 7;
            this.label9.Text = "Filter family name containing:";
            this.label9.TextAlign = ContentAlignment.TopRight;
            this.comboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Location = new Point(99, 14);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new Size(196, 21);
            this.comboBox1.TabIndex = 1;
            this.comboBox1.SelectedIndexChanged += new EventHandler(this.comboBox1_SelectedIndexChanged);
            this.label8.AutoSize = true;
            this.label8.Location = new Point(13, 19);
            this.label8.Name = "label8";
            this.label8.Size = new Size(76, 13);
            this.label8.TabIndex = 5;
            this.label8.Text = "Filter category:";
            this.button2.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.button2.Location = new Point(15, 530);
            this.button2.Name = "button2";
            this.button2.Size = new Size(74, 22);
            this.button2.TabIndex = 12;
            this.button2.Text = "Check all";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new EventHandler(this.button2_Click);
            this.groupBox3.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.groupBox3.Controls.Add((Control)this.textBox3);
            this.groupBox3.Controls.Add((Control)this.label10);
            this.groupBox3.Controls.Add((Control)this.label11);
            this.groupBox3.Controls.Add((Control)this.label12);
            this.groupBox3.Controls.Add((Control)this.numericUpDown2);
            this.groupBox3.Location = new Point(778, 175);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(168, 72);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Suffix";
            this.textBox3.Location = new Point(82, 43);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new Size(78, 20);
            this.textBox3.TabIndex = 8;
            this.textBox3.TextChanged += new EventHandler(this.textBox3_TextChanged);
            this.label10.AutoSize = true;
            this.label10.Location = new Point(8, 46);
            this.label10.Name = "label10";
            this.label10.Size = new Size(56, 13);
            this.label10.TabIndex = 3;
            this.label10.Text = "Add suffix:";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(125, 19);
            this.label11.Name = "label11";
            this.label11.Size = new Size(33, 13);
            this.label11.TabIndex = 2;
            this.label11.Text = "chars";
            this.label12.AutoSize = true;
            this.label12.Location = new Point(8, 19);
            this.label12.Name = "label12";
            this.label12.Size = new Size(66, 13);
            this.label12.TabIndex = 1;
            this.label12.Text = "Remove last";
            this.numericUpDown2.Location = new Point(82, 17);
            this.numericUpDown2.Maximum = new Decimal(new int[4]
            {
        99,
        0,
        0,
        0
            });
            this.numericUpDown2.Name = "numericUpDown2";
            this.numericUpDown2.Size = new Size(38, 20);
            this.numericUpDown2.TabIndex = 7;
            this.numericUpDown2.ValueChanged += new EventHandler(this.numericUpDown2_ValueChanged);
            this.groupBox4.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.groupBox4.Controls.Add((Control)this.textBox5);
            this.groupBox4.Controls.Add((Control)this.textBox4);
            this.groupBox4.Controls.Add((Control)this.label13);
            this.groupBox4.Controls.Add((Control)this.label15);
            this.groupBox4.Location = new Point(778, 264);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(168, 77);
            this.groupBox4.TabIndex = 3;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Find and replace";
            this.textBox5.Location = new Point(82, 46);
            this.textBox5.Name = "textBox5";
            this.textBox5.Size = new Size(77, 20);
            this.textBox5.TabIndex = 10;
            this.textBox5.TextChanged += new EventHandler(this.textBox5_TextChanged);
            this.textBox4.Location = new Point(82, 19);
            this.textBox4.Name = "textBox4";
            this.textBox4.Size = new Size(77, 20);
            this.textBox4.TabIndex = 9;
            this.textBox4.TextChanged += new EventHandler(this.textBox4_TextChanged);
            this.label13.AutoSize = true;
            this.label13.Location = new Point(8, 49);
            this.label13.Name = "label13";
            this.label13.Size = new Size(72, 13);
            this.label13.TabIndex = 3;
            this.label13.Text = "Replace with:";
            this.label15.AutoSize = true;
            this.label15.Location = new Point(8, 22);
            this.label15.Name = "label15";
            this.label15.Size = new Size(50, 13);
            this.label15.TabIndex = 1;
            this.label15.Text = "Find text:";
            this.button5.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.button5.Location = new Point(95, 530);
            this.button5.Name = "button5";
            this.button5.Size = new Size(80, 22);
            this.button5.TabIndex = 13;
            this.button5.Text = "Uncheck all";
            this.button5.UseVisualStyleBackColor = true;
            this.button5.Click += new EventHandler(this.button5_Click);
            this.linkLabelSite.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.linkLabelSite.AutoSize = true;
            this.linkLabelSite.Cursor = Cursors.Hand;
            this.linkLabelSite.Location = new Point(118, 591);
            this.linkLabelSite.Name = "linkLabelSite";
            this.linkLabelSite.Size = new Size(103, 13);
            this.linkLabelSite.TabIndex = 22;
            this.linkLabelSite.TabStop = true;
            this.linkLabelSite.Text = "http://pangolin.tools";
            this.labelSite.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.labelSite.Cursor = Cursors.Hand;
            this.labelSite.Font = new Font("Microsoft Sans Serif", 8f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
            this.labelSite.Location = new Point(117, 573);
            this.labelSite.Margin = new Padding(2, 0, 2, 0);
            this.labelSite.Name = "labelSite";
            this.labelSite.Size = new Size(130, 13);
            this.labelSite.TabIndex = 21;
            this.labelSite.Text = "Get more Revit add-ins";
            this.labelSite.TextAlign = ContentAlignment.MiddleLeft;
            this.labelSite.UseCompatibleTextRendering = true;
            this.label14.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.label14.Font = new Font("Microsoft Sans Serif", 7.5f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
            this.label14.Location = new Point(778, 598);
            this.label14.Margin = new Padding(2, 0, 2, 0);
            this.label14.Name = "label14";
            this.label14.Size = new Size(123, 13);
            this.label14.TabIndex = 23;
            this.label14.Text = "by Corentin Gartner";
            this.label14.UseCompatibleTextRendering = true;
            this.groupBox5.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.groupBox5.Controls.Add((Control)this.label19);
            this.groupBox5.Controls.Add((Control)this.numericUpDown4);
            this.groupBox5.Controls.Add((Control)this.textBox6);
            this.groupBox5.Controls.Add((Control)this.label16);
            this.groupBox5.Controls.Add((Control)this.label17);
            this.groupBox5.Controls.Add((Control)this.label18);
            this.groupBox5.Controls.Add((Control)this.numericUpDown3);
            this.groupBox5.Location = new Point(778, 356);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(168, 102);
            this.groupBox5.TabIndex = 7;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Modify at index";
            this.label19.AutoSize = true;
            this.label19.Location = new Point(8, 21);
            this.label19.Name = "label19";
            this.label19.Size = new Size(72, 13);
            this.label19.TabIndex = 7;
            this.label19.Text = "Start at index:";
            this.numericUpDown4.Location = new Point(82, 19);
            this.numericUpDown4.Maximum = new Decimal(new int[4]
            {
        99,
        0,
        0,
        0
            });
            this.numericUpDown4.Name = "numericUpDown4";
            this.numericUpDown4.Size = new Size(38, 20);
            this.numericUpDown4.TabIndex = 8;
            this.numericUpDown4.ValueChanged += new EventHandler(this.numericUpDown4_ValueChanged);
            this.textBox6.Location = new Point(82, 71);
            this.textBox6.Name = "textBox6";
            this.textBox6.Size = new Size(78, 20);
            this.textBox6.TabIndex = 6;
            this.textBox6.TextChanged += new EventHandler(this.textBox6_TextChanged);
            this.label16.AutoSize = true;
            this.label16.Location = new Point(8, 74);
            this.label16.Name = "label16";
            this.label16.Size = new Size(56, 13);
            this.label16.TabIndex = 3;
            this.label16.Text = "Insert text:";
            this.label17.AutoSize = true;
            this.label17.Location = new Point(125, 47);
            this.label17.Name = "label17";
            this.label17.Size = new Size(33, 13);
            this.label17.TabIndex = 2;
            this.label17.Text = "chars";
            this.label18.AutoSize = true;
            this.label18.Location = new Point(8, 47);
            this.label18.Name = "label18";
            this.label18.Size = new Size(47, 13);
            this.label18.TabIndex = 1;
            this.label18.Text = "Remove";
            this.numericUpDown3.Location = new Point(82, 45);
            this.numericUpDown3.Maximum = new Decimal(new int[4]
            {
        99,
        0,
        0,
        0
            });
            this.numericUpDown3.Name = "numericUpDown3";
            this.numericUpDown3.Size = new Size(38, 20);
            this.numericUpDown3.TabIndex = 5;
            this.numericUpDown3.ValueChanged += new EventHandler(this.numericUpDown3_ValueChanged);
            this.checkBox1.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.checkBox1.ImageAlign = ContentAlignment.MiddleLeft;
            this.checkBox1.Location = new Point(778, 470);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new Size(99, 17);
            this.checkBox1.TabIndex = 24;
            this.checkBox1.Text = "To uppercase";
            this.checkBox1.UseVisualStyleBackColor = true;
            this.checkBox1.CheckedChanged += new EventHandler(this.checkBox1_CheckedChanged);
            this.checkBox2.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.checkBox2.ImageAlign = ContentAlignment.MiddleLeft;
            this.checkBox2.Location = new Point(778, 489);
            this.checkBox2.Name = "checkBox2";
            this.checkBox2.Size = new Size(99, 17);
            this.checkBox2.TabIndex = 25;
            this.checkBox2.Text = "To lowercase";
            this.checkBox2.UseVisualStyleBackColor = true;
            this.checkBox2.CheckedChanged += new EventHandler(this.checkBox2_CheckedChanged);
            this.checkBox3.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.checkBox3.ImageAlign = ContentAlignment.MiddleLeft;
            this.checkBox3.Location = new Point(778, 509);
            this.checkBox3.Name = "checkBox3";
            this.checkBox3.Size = new Size(120, 17);
            this.checkBox3.TabIndex = 26;
            this.checkBox3.Text = "Remove diacritics";
            this.checkBox3.UseVisualStyleBackColor = true;
            this.checkBox3.CheckedChanged += new EventHandler(this.checkBox3_CheckedChanged);
            this.label20.AutoSize = true;
            this.label20.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
            this.label20.Location = new Point(13, 65);
            this.label20.Name = "label20";
            this.label20.Size = new Size(369, 17);
            this.label20.TabIndex = 8;
            this.label20.Text = "Check below the items to apply renaming rules to:";
            this.label21.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label21.AutoSize = true;
            this.label21.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
            this.label21.Location = new Point(803, 65);
            this.label21.Name = "label21";
            this.label21.Size = new Size(126, 17);
            this.label21.TabIndex = 27;
            this.label21.Text = "Renaming rules:";
            this.label22.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label22.AutoSize = true;
            this.label22.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Underline, GraphicsUnit.Point, (byte)0);
            this.label22.ForeColor = SystemColors.Highlight;
            this.label22.Location = new Point(794, 535);
            this.label22.Name = "label22";
            this.label22.Size = new Size(138, 13);
            this.label22.TabIndex = 33;
            this.label22.Text = "How to use numbering rules";
            this.listView1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.listView1.CheckBoxes = true;
            this.listView1.Columns.AddRange(new ColumnHeader[4]
            {
        this.columnHeader4,
        this.columnHeader1,
        this.columnHeader2,
        this.columnHeader3
            });
            this.listView1.FullRowSelect = true;
            this.listView1.GridLines = true;
            this.listView1.HideSelection = false;
            this.listView1.LineAfter = -1;
            this.listView1.LineBefore = -1;
            this.listView1.Location = new System.Drawing.Point(15, 87);
            this.listView1.Name = "listView1";
            this.listView1.Size = new Size(746, 437);
            this.listView1.TabIndex = 1;
            this.listView1.TabStop = false;
            this.listView1.UseCompatibleStateImageBehavior = false;
            this.listView1.View = View.Details;
            this.listView1.ColumnClick += new ColumnClickEventHandler(this.listView1_ColumnClick);
            this.listView1.ColumnWidthChanged += new ColumnWidthChangedEventHandler(this.listView1_ColumnWidthChanged);
            this.listView1.ItemCheck += new ItemCheckEventHandler(this.listView1_ItemCheck);
            this.listView1.KeyDown += new KeyEventHandler(this.listView1_KeyDown);
            this.listView1.Leave += new EventHandler(this.listView1_Leave);
            this.listView1.MouseDown += new MouseEventHandler(this.listView1_MouseDown);
            this.listView1.MouseMove += new MouseEventHandler(this.listView1_MouseMove);
            this.listView1.MouseUp += new MouseEventHandler(this.listView1_MouseUp);
            this.columnHeader4.Text = "";
            this.columnHeader4.Width = 20;
            this.columnHeader1.Text = "Category";
            this.columnHeader1.Width = 200;
            this.columnHeader2.Text = "Family Name";
            this.columnHeader2.Width = 250;
            this.columnHeader3.Text = "New Family Name Preview";
            this.columnHeader3.Width = 250;
            this.pictureBox3.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.pictureBox3.Cursor = Cursors.Default;
            this.pictureBox3.Image = (Image)Resources.helpicon16;
            this.pictureBox3.Location = new System.Drawing.Point(778, 534);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new Size(16, 16);
            this.pictureBox3.SizeMode = PictureBoxSizeMode.AutoSize;
            this.pictureBox3.TabIndex = 32;
            this.pictureBox3.TabStop = false;
            this.pictureBoxSite.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.pictureBoxSite.BackColor = System.Drawing.Color.Transparent;
            this.pictureBoxSite.Cursor = Cursors.Hand;
            this.pictureBoxSite.Image = (Image)Resources.logo230x50;
            this.pictureBoxSite.InitialImage = (Image)null;
            this.pictureBoxSite.Location = new System.Drawing.Point(15, 564);
            this.pictureBoxSite.Name = "pictureBoxSite";
            this.pictureBoxSite.Size = new Size(232, 50);
            this.pictureBoxSite.TabIndex = 20;
            this.pictureBoxSite.TabStop = false;
            this.AutoScaleDimensions = new SizeF(6f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(958, 626);
            this.Controls.Add((System.Windows.Forms.Control)this.label22);
            this.Controls.Add((System.Windows.Forms.Control)this.pictureBox3);
            this.Controls.Add((System.Windows.Forms.Control)this.label21);
            this.Controls.Add((System.Windows.Forms.Control)this.label20);
            this.Controls.Add((System.Windows.Forms.Control)this.checkBox3);
            this.Controls.Add((System.Windows.Forms.Control)this.checkBox2);
            this.Controls.Add((System.Windows.Forms.Control)this.checkBox1);
            this.Controls.Add((System.Windows.Forms.Control)this.groupBox5);
            this.Controls.Add((System.Windows.Forms.Control)this.label14);
            this.Controls.Add((System.Windows.Forms.Control)this.linkLabelSite);
            this.Controls.Add((System.Windows.Forms.Control)this.labelSite);
            this.Controls.Add((System.Windows.Forms.Control)this.pictureBoxSite);
            this.Controls.Add((System.Windows.Forms.Control)this.button5);
            this.Controls.Add((System.Windows.Forms.Control)this.groupBox4);
            this.Controls.Add((System.Windows.Forms.Control)this.groupBox3);
            this.Controls.Add((System.Windows.Forms.Control)this.button2);
            this.Controls.Add((System.Windows.Forms.Control)this.groupBox2);
            this.Controls.Add((System.Windows.Forms.Control)this.groupBox1);
            this.Controls.Add((System.Windows.Forms.Control)this.label2);
            this.Controls.Add((System.Windows.Forms.Control)this.label1);
            this.Controls.Add((System.Windows.Forms.Control)this.button1);
            this.Controls.Add((System.Windows.Forms.Control)this.listView1);
            this.Controls.Add((System.Windows.Forms.Control)this.linkLabel1);
            this.Controls.Add((System.Windows.Forms.Control)this.label5);
            this.Icon = (Icon)componentResourceManager.GetObject("$this.Icon");
            this.KeyPreview = true;
            this.Margin = new Padding(2);
            this.MinimumSize = new Size(850, 665);
            this.Name = nameof(MainForm);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "Magic Family Rename Tool - Rename Families";
            this.Shown += new EventHandler(this.MainForm_Shown);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.numericUpDown1.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.numericUpDown2.EndInit();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.numericUpDown4.EndInit();
            this.numericUpDown3.EndInit();
            ((ISupportInitialize)this.pictureBox3).EndInit();
            ((ISupportInitialize)this.pictureBoxSite).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion
    }
}